openapi: 3.0.1
info:
  title: monster-bronze-dragon-wyrmling
  x-cortex-tag: monster-bronze-dragon-wyrmling
  x-cortex-custom-metadata:
    alignment: chaotic-good
    type: dragon
    challenge_rating: 3
    legendary: false
    source: dnd-5e
  x-cortex-type: monster
